## TKX 피트니스에 오신 것을 환영합니다!

안녕하세요! TKX 피트니스 데이터분석팀에 오신 것을 환영합니다.

TKX는 국내 최대의 프렌차이즈 피트니스 센터로서, 매월 수 천명에 달하는 신규 회원을 받아 데이터를 분석하고 있습니다.

TKX 피트니스의 장점은 프로그래밍 언어 파이썬(Python)과 데이터 분석 프레임워크 판다스(Pandas)를 활용한 면밀한 데이터 분석입니다. 이 데이터 분석을 바탕으로 KTX의 오퍼레이션 팀 / 코칭 팀은 피트니스 센터에 방문하는 고객 분들, 그리고 방문하지 않는 고객 분들에게도 최선의 맞춤 서비스를 제공해 드리고 있습니다.

오늘 이 노트북을 받은 분이 해주셔야 하는 일은 2016년도 1월부터 2017년도 12월까지의 신규 가입 고객 데이터를 받아와, 차후에 데이터분석을 더 용이하게 할 수 있도록 데이터를 정리해주는 작업, 일명 데이터 클리닝(Data Cleaning) 작업입니다.

저희 TKX 피트니스는 언제나 잘 정리되어 있는 고객 정보를 받아서 데이터 분석팀에게 맡길려고 노력하고 있으나, (이 노트북을 받은 분들도 아시겠지만) 현실은 언제나 100% 잘 정리되어있는 데이터를 받아오기가 어렵습니다.

때문에 이번 시간에는 신규 가입 고객 데이터를 분석하여, 데이터에 몇몇 누락된 부분이나 잘못 기입된 부분 등을 판다스로 정리하고 그 결과를 분석하는 일을 해주셨으면 합니다.

데이터는 다음의 URL [https://goo.gl/8XGH4T](https://goo.gl/8XGH4T) 에서 다운받을 수 있습니다. 데이터를 다운받아 읽어온 뒤, 하기에 적어놓은 내용대로 데이터를 분석 및 정리를 해주세요.




## Load Dataset

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [2]:
user_info = pd.read_csv('./data/tkx-user-data.csv')

In [3]:
user_info.head()

이름  성별           전화번호   나이 현재 체중 목표 체중    키         회원 가입일      회원 정보 갱신일  \
0  안원준  남성  010-2292-6251  31세    78    68  176  2016년 07월 05일  2016년 07월 05일   
1  유세아  여성    01045795881   39  56kg  51kg  172  2016년 10월 02일  2016년 11월 29일   
2  송솔은  여성  010-7719-8346  NaN    29    21  167  2017년 09월 06일  2017년 09월 06일   
3  백서원  여성    01011947169   36    67    65    0  2017년 06월 02일  2017년 07월 28일   
4  박서은  여성  010-2575-6398   42    60    57  167  2017년 05월 07일  2017년 05월 07일   

  흡연 여부 음주 여부 가입 개월 수 개인상담 요청  
0   아니오  주 1회     0개월     아니요  
1     예  월 1회     0개월     아니요  
2     예  주 1회     0개월     아니요  
3     예  안 마심     0개월     아니요  
4   아니오  안 마심     0개월       예

In [4]:
user_info.shape

(106839, 13)

## 실습

** 1. 텍스트로 된 흡연 여부(예/아니오)를 True/False 로 바꾸기 **

In [5]:
user_info['흡연 여부'].value_counts()

아니오    85468
예      21371
Name: 흡연 여부, dtype: int64

In [6]:
user_info['흡연 여부'] = user_info['흡연 여부'] == '예'

In [7]:
user_info['흡연 여부'].value_counts()

False    85468
True     21371
Name: 흡연 여부, dtype: int64

In [8]:
user_info.head()

이름  성별           전화번호   나이 현재 체중 목표 체중    키         회원 가입일      회원 정보 갱신일  \
0  안원준  남성  010-2292-6251  31세    78    68  176  2016년 07월 05일  2016년 07월 05일   
1  유세아  여성    01045795881   39  56kg  51kg  172  2016년 10월 02일  2016년 11월 29일   
2  송솔은  여성  010-7719-8346  NaN    29    21  167  2017년 09월 06일  2017년 09월 06일   
3  백서원  여성    01011947169   36    67    65    0  2017년 06월 02일  2017년 07월 28일   
4  박서은  여성  010-2575-6398   42    60    57  167  2017년 05월 07일  2017년 05월 07일   

   흡연 여부 음주 여부 가입 개월 수 개인상담 요청  
0  False  주 1회     0개월     아니요  
1   True  월 1회     0개월     아니요  
2   True  주 1회     0개월     아니요  
3   True  안 마심     0개월     아니요  
4  False  안 마심     0개월       예

** 2. 나이에서 0세라고 되어있는 것을 NaN으로 바꾸기 **

- 0인 항목을 찾기 위해 value_counts() 메소드를 이용했는데 이걸로는 확인하기 어려웠다.

In [9]:
user_info[user_info['나이'] == 0]

Empty DataFrame
Columns: [이름, 성별, 전화번호, 나이, 현재 체중, 목표 체중, 키, 회원 가입일, 회원 정보 갱신일, 흡연 여부, 음주 여부, 가입 개월 수, 개인상담 요청]
Index: []

- 나이가 0인 항목이 없는데?

** 3. 나이 컬럼을 정리하기 **

In [10]:
user_info['나이'].unique()

array(['31세', '39', nan, '36', '42', '32', '27', '29', '37', '37세', '34',
       '40', '33 세', '35', '30', '28', '50', '43', '31', '27세', '20',
       '36세', '22', '33세', '33', '25', '38', '23', '38 세', '26', '34 세',
       '2', '31 세', '35 세', '49', '41', '24', '44', '39세', '105', '118',
       '36 세', '5', '28 세', '37 세', '19', '32 세', '21', '25 세', '42세',
       '44세', '46', '24 세', '85', '26 세', '39 세', '43세', '47', '82',
       '38세', '45세', '30 세', '19세', '32세', '20세', '116', '40세', '34세',
       '6', '6 세', '47세', '16', '81', '30세', '24세', '45', '18', '20 세',
       '42 세', '26세', '27 세', '35세', '110', '4', '8', '21 세', '115',
       '25세', '28세', '29세', '7', '80세', '21세', '3', '96 세', '23 세', '15',
       '119', '14', '29 세', '5세', '91', '44 세', '112', '40 세', '109',
       '17', '92', '51', '16세', '94', '22 세', '41세', '5 세', '41 세', '48',
       '102', '22세', '114', '84', '106', '50세', '96', '87', '95', '23세',
       '49세', '8 세', '111', '46세', '101', '97세', '7 세', '112세', '11

In [11]:
def clean_num_col(old, new):
    def wrapper(data):
        if type(data) is str:
            num = data.replace(old, new)
            return int(num)
        return data
    return wrapper

In [12]:
clean_age = clean_num_col('세', '')
user_info['나이'] = user_info['나이'].map(clean_age)

In [13]:
user_info['나이'].unique()

array([ 31.,  39.,  nan,  36.,  42.,  32.,  27.,  29.,  37.,  34.,  40.,
        33.,  35.,  30.,  28.,  50.,  43.,  20.,  22.,  25.,  38.,  23.,
        26.,   2.,  49.,  41.,  24.,  44., 105., 118.,   5.,  19.,  21.,
        46.,  85.,  47.,  82.,  45., 116.,   6.,  16.,  81.,  18., 110.,
         4.,   8., 115.,   7.,  80.,   3.,  96.,  15., 119.,  14.,  91.,
       112., 109.,  17.,  92.,  51.,  94.,  48., 102., 114.,  84., 106.,
        87.,  95., 111., 101.,  97., 113.,  86., 107.,  90., 103., 117.,
        88., 100., 108.,  13.,  99., 104.,  93.,  98.,  52.,  83.,  53.,
        89.,  11.,  54.,  12.])

** 4. 평균(mean) / 최소(min) / 최대(max) 나이 구하기 **

In [14]:
age = user_info['나이']
(age.mean(), age.min(), age.max())

(33.29973284545577, 2.0, 119.0)

** 5. 컬럼의 순서를 조금 더 직관적으로 바꾸기 **

In [15]:
user_info.head()

이름  성별           전화번호    나이 현재 체중 목표 체중    키         회원 가입일  \
0  안원준  남성  010-2292-6251  31.0    78    68  176  2016년 07월 05일   
1  유세아  여성    01045795881  39.0  56kg  51kg  172  2016년 10월 02일   
2  송솔은  여성  010-7719-8346   NaN    29    21  167  2017년 09월 06일   
3  백서원  여성    01011947169  36.0    67    65    0  2017년 06월 02일   
4  박서은  여성  010-2575-6398  42.0    60    57  167  2017년 05월 07일   

       회원 정보 갱신일  흡연 여부 음주 여부 가입 개월 수 개인상담 요청  
0  2016년 07월 05일  False  주 1회     0개월     아니요  
1  2016년 11월 29일   True  월 1회     0개월     아니요  
2  2017년 09월 06일   True  주 1회     0개월     아니요  
3  2017년 07월 28일   True  안 마심     0개월     아니요  
4  2017년 05월 07일  False  안 마심     0개월       예

In [16]:
private_info = ['이름', '성별', '나이', '키', '현재 체중', '목표 체중', '흡연 여부', '음주 여부', '전화번호']
etc_info = ['개인상담 요청', '가입 개월 수', '회원 가입일', '회원 정보 갱신일']

In [17]:
user_info_ordered = user_info[private_info + etc_info]
user_info_ordered.head()

이름  성별    나이    키 현재 체중 목표 체중  흡연 여부 음주 여부           전화번호 개인상담 요청 가입 개월 수  \
0  안원준  남성  31.0  176    78    68  False  주 1회  010-2292-6251     아니요     0개월   
1  유세아  여성  39.0  172  56kg  51kg   True  월 1회    01045795881     아니요     0개월   
2  송솔은  여성   NaN  167    29    21   True  주 1회  010-7719-8346     아니요     0개월   
3  백서원  여성  36.0    0    67    65   True  안 마심    01011947169     아니요     0개월   
4  박서은  여성  42.0  167    60    57  False  안 마심  010-2575-6398       예     0개월   

          회원 가입일      회원 정보 갱신일  
0  2016년 07월 05일  2016년 07월 05일  
1  2016년 10월 02일  2016년 11월 29일  
2  2017년 09월 06일  2017년 09월 06일  
3  2017년 06월 02일  2017년 07월 28일  
4  2017년 05월 07일  2017년 05월 07일

## 과제(초급)

### 데이터를 사용하기 용이하게 정리하기

**6. 컬럼 이름 바꾸기**

보통 프로그래밍을 할 때 한글 컬럼을 사용하면 다양한 문제로 불편을 겪을 때가 많습니다.

그러므로 컬럼을 전부 한글에서 영어로 바꿔주세요. 컬럼명은 다음과 같이 바꿔주시면 됩니다.

* 이름 - Name
* 성별 - Gender
* 전화번호 - Phone Number
* 나이 - Age
* 현재 체중 - Current Weight
* 목표 체종 - Goal Weight
* 키 - Height
* 흡연 여부 - Smoking
* 음주 여부 - Drinking
* 개인상담 요청 - Request Counselling
* 회원 가입일 - Joined At
* 회원 정보 갱신일 - Updated At
* 가입 개월 수 - Paid Plan

In [18]:
col_name = {'이름': 'Name',
            '성별': 'Gender',
            '전화번호': 'Phone Number',
            '나이': 'Age',
            '현재 체중': 'Current Weight',
            '목표 체중': 'Goal Weight',
            '키': 'Height',
            '흡연 여부': 'Smoking',
            '음주 여부': 'Drinking',
            '개인상담 요청': 'Request Counselling',
            '회원 가입일': 'Joined At',
            '회원 정보 갱신일': 'Updated At',
            '가입 개월 수': 'Paid Plan'}

In [19]:
user_info2 = user_info_ordered.rename(columns=col_name)
user_info2.head()

Name Gender   Age Height Current Weight Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0    176             78          68    False     주 1회   
1  유세아     여성  39.0    172           56kg        51kg     True     월 1회   
2  송솔은     여성   NaN    167             29          21     True     주 1회   
3  백서원     여성  36.0      0             67          65     True     안 마심   
4  박서은     여성  42.0    167             60          57    False     안 마심   

    Phone Number Request Counselling Paid Plan      Joined At     Updated At  
0  010-2292-6251                 아니요       0개월  2016년 07월 05일  2016년 07월 05일  
1    01045795881                 아니요       0개월  2016년 10월 02일  2016년 11월 29일  
2  010-7719-8346                 아니요       0개월  2017년 09월 06일  2017년 09월 06일  
3    01011947169                 아니요       0개월  2017년 06월 02일  2017년 07월 28일  
4  010-2575-6398                   예       0개월  2017년 05월 07일  2017년 05월 07일

** 7. '상담 요청' 컬럼을 예/아니오 에서 True/False로 바꿔주세요 **

In [20]:
user_info2['Request Counselling'].value_counts()

아니요    96260
예      10579
Name: Request Counselling, dtype: int64

In [21]:
user_info2['Request Counselling'] = user_info2['Request Counselling'] == '예'

In [22]:
user_info2['Request Counselling'].value_counts()

False    96260
True     10579
Name: Request Counselling, dtype: int64

**8. '가입 개월 수' 컬럼을 분석해서, 무료(0개월)인 경우를 True로, 유료인 경우(3, 6, 9, 12개월)를 False로 보여주는 새로운 컬럼을 만들어주세요.**

In [23]:
user_info2['Paid Plan'].value_counts()

0개월     74955
3개월     21250
6개월      7291
12개월     3343
Name: Paid Plan, dtype: int64

In [24]:
user_info2['Is Free'] = user_info2['Paid Plan'] == '0개월'

In [25]:
user_info2.head()

Name Gender   Age Height Current Weight Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0    176             78          68    False     주 1회   
1  유세아     여성  39.0    172           56kg        51kg     True     월 1회   
2  송솔은     여성   NaN    167             29          21     True     주 1회   
3  백서원     여성  36.0      0             67          65     True     안 마심   
4  박서은     여성  42.0    167             60          57    False     안 마심   

    Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
0  010-2292-6251                False       0개월  2016년 07월 05일  2016년 07월 05일   
1    01045795881                False       0개월  2016년 10월 02일  2016년 11월 29일   
2  010-7719-8346                False       0개월  2017년 09월 06일  2017년 09월 06일   
3    01011947169                False       0개월  2017년 06월 02일  2017년 07월 28일   
4  010-2575-6398                 True       0개월  2017년 05월 07일  2017년 05월 07일   

   Is Free  
0     True  
1     True  
2     True  
3     True  
4     True

In [26]:
user_info2[['Paid Plan', 'Is Free']].head(10)

Paid Plan  Is Free
0       0개월     True
1       0개월     True
2       0개월     True
3       0개월     True
4       0개월     True
5       3개월    False
6      12개월    False
7       0개월     True
8       0개월     True
9       3개월    False

### 컬럼의 형태를 하나로 통일하고, 빈 값이나 outlier들을 NaN으로 바꾸기

** 9. 전화번호 컬럼을 정리해주세요. 다음과 같이 정리해주시면 됩니다. **
  * unknown 이라고 표시되어 있는 전화번호는 빈 전화번호입니다. 이를 NaN으로 바꿔주세요.

In [27]:
# 일단 user_info2가 어떻게 생겼나보자.
user_info2.head()

Name Gender   Age Height Current Weight Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0    176             78          68    False     주 1회   
1  유세아     여성  39.0    172           56kg        51kg     True     월 1회   
2  송솔은     여성   NaN    167             29          21     True     주 1회   
3  백서원     여성  36.0      0             67          65     True     안 마심   
4  박서은     여성  42.0    167             60          57    False     안 마심   

    Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
0  010-2292-6251                False       0개월  2016년 07월 05일  2016년 07월 05일   
1    01045795881                False       0개월  2016년 10월 02일  2016년 11월 29일   
2  010-7719-8346                False       0개월  2017년 09월 06일  2017년 09월 06일   
3    01011947169                False       0개월  2017년 06월 02일  2017년 07월 28일   
4  010-2575-6398                 True       0개월  2017년 05월 07일  2017년 05월 07일   

   Is Free  
0     True  
1     True  
2     True  
3     True  
4     True

In [28]:
# 전화번호 컬럼은 Phone Number로 변경했다.
# 어떤 데이터가 있는지 보자.
# 전화번호니까 분포를 볼 필요는 없을 것 같다. 그냥 Series를 출력한다.
user_info2['Phone Number'].head(10)

0    010-2292-6251
1      01045795881
2    010-7719-8346
3      01011947169
4    010-2575-6398
5    010-7299-1288
6    010-2132-4484
7      01019249265
8      01045337615
9      01036423916
Name: Phone Number, dtype: object

In [29]:
# 먼저 unknown인 것을 출력해보자.
user_info2[user_info2['Phone Number'] == 'unknown'].head(10)

Name Gender   Age Height Current Weight Goal Weight  Smoking Drinking  \
10  한대권     남성  37.0      0             78          69    False     주 1회   
16  황서은     여성  34.0    172             59          56    False     월 2회   
28  박성원     남성  34.0      0              0           0    False     월 2회   
35  한대윤      남   NaN    176           82kg        75kg    False     월 1회   
49  황은우     남성  37.0    174           82kg        81kg    False     주 1회   
54  강지빈     남성  36.0    176             82          77     True     월 1회   
60  고윤찬     남성  38.0    171             84          78    False     월 2회   
74  황승엽   male  34.0    172             84          79     True     월 2회   
78  고서아      여  34.0    170             55          52    False     주 2회   
80  오은찬     남성   2.0    181             82          74    False     월 2회   

   Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
10      unknown                False       3개월  2016년 04월 10일  2016년 04월 10일   
16      unknown                False       0개월  2016년 08월 17일  2016년 08월 29일   
28      unknown                False       6개월  2016년 09월 21일  2016년 09월 21일   
35      unknown                False       0개월  2017년 08월 13일  2017년 08월 13일   
49      unknown                False       0개월  2017년 11월 10일  2018년 02월 16일   
54      unknown                False       0개월  2016년 02월 24일  2016년 02월 24일   
60      unknown                False       3개월  2017년 07월 07일  2017년 08월 24일   
74      unknown                False       3개월  2017년 07월 10일  2017년 07월 10일   
78      unknown                 True       0개월  2016년 03월 15일  2016년 03월 15일   
80      unknown                False       0개월  2016년 06월 11일  2016년 06월 11일   

    Is Free  
10    False  
16     True  
28    False  
35     True  
49     True  
54     True  
60    False  
74    False  
78     True  
80     True

- **unknown을 NaN으로 변환한다.**

In [30]:
user_info2[user_info2['Phone Number'] == 'unknown'] = np.nan

In [31]:
# unknown은 없는 것이 확인됐다.
user_info2[user_info2['Phone Number'] == 'unknown']

Empty DataFrame
Columns: [Name, Gender, Age, Height, Current Weight, Goal Weight, Smoking, Drinking, Phone Number, Request Counselling, Paid Plan, Joined At, Updated At, Is Free]
Index: []

In [32]:
user_info2['Phone Number'].isnull().sum()

10640

In [33]:
user_info2['Phone Number'].head(10)

0    010-2292-6251
1      01045795881
2    010-7719-8346
3      01011947169
4    010-2575-6398
5    010-7299-1288
6    010-2132-4484
7      01019249265
8      01045337615
9      01036423916
Name: Phone Number, dtype: object

** 10. 키(cm) 컬럼을 정리해주세요. 다음과 같이 정리해주시면 됩니다.** 

* 다양한 형태로 표현되어 있는 키 컬럼(?, ?cm, ? cm 등)을 숫자로 통일해주세요.
* 키가 0으로 되어있으면 NaN으로 바꿔주세요.
* 키가 너무 작거나(140cm 이하) 너무 크면(210cm 이상) 마찬가지로 NaN으로 바꿔주세요.

In [34]:
user_info2.head()

Name Gender   Age Height Current Weight Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0    176             78          68      0.0     주 1회   
1  유세아     여성  39.0    172           56kg        51kg      1.0     월 1회   
2  송솔은     여성   NaN    167             29          21      1.0     주 1회   
3  백서원     여성  36.0      0             67          65      1.0     안 마심   
4  박서은     여성  42.0    167             60          57      0.0     안 마심   

    Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
0  010-2292-6251                  0.0       0개월  2016년 07월 05일  2016년 07월 05일   
1    01045795881                  0.0       0개월  2016년 10월 02일  2016년 11월 29일   
2  010-7719-8346                  0.0       0개월  2017년 09월 06일  2017년 09월 06일   
3    01011947169                  0.0       0개월  2017년 06월 02일  2017년 07월 28일   
4  010-2575-6398                  1.0       0개월  2017년 05월 07일  2017년 05월 07일   

   Is Free  
0      1.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0

In [35]:
user_info2['Height'].unique()

array(['176', '172', '167', '0', '171', '177', nan, '164', '170', '178',
       '182', '184', '217 cm', '159', '169', '175', '173', '121cm', '156',
       '168', '166', '165', '206cm', '181', '177 cm', '157', '172cm',
       '180 cm', '175cm', '179cm', '179', '161', '183', '132', '185',
       '180', '172 cm', '169 cm', '174 cm', '162', '174cm', '170 cm',
       '188', '160', '171cm', '174', '158', '176 cm', '173 cm', '167 cm',
       '162cm', '134cm', '234', '159cm', '155', '180cm', '182cm', '178cm',
       '104', '126', '163 cm', '162 cm', '166 cm', '187', '114', '163',
       '106', '164cm', '173cm', '182 cm', '166cm', '181cm', '186 cm',
       '192', '165 cm', '160 cm', '181 cm', '170cm', '171 cm', '179 cm',
       '186', '201', '243', '168cm', '208', '219', '178 cm', '176cm',
       '177cm', '152', '238', '225', '211', '184 cm', '183cm', '155cm',
       '169cm', '167cm', '110', '247', '246', '165cm', '161cm', '109',
       '183 cm', '222', '191', '125', '175 cm', '206', '154', '16

In [36]:
clean_height = clean_num_col('cm', '')
user_info2['Height'] = user_info2['Height'].map(clean_height)

In [37]:
user_info2['Height'].unique()

array([176., 172., 167.,   0., 171., 177.,  nan, 164., 170., 178., 182.,
       184., 217., 159., 169., 175., 173., 121., 156., 168., 166., 165.,
       206., 181., 157., 180., 179., 161., 183., 132., 185., 174., 162.,
       188., 160., 158., 134., 234., 155., 104., 126., 163., 187., 114.,
       106., 186., 192., 201., 243., 208., 219., 152., 238., 225., 211.,
       110., 247., 246., 109., 222., 191., 125., 154., 212., 230., 218.,
       119., 242., 129., 124., 107., 137., 189., 210., 213., 200., 131.,
       241., 100., 122., 101., 215., 209., 224., 190., 130., 127., 214.,
       139., 153., 220., 231., 193., 227., 102., 136., 205., 228., 117.,
       115., 138., 235., 108., 203., 133., 207., 149., 236., 120., 128.,
       233., 239., 245., 226., 216., 151., 103., 221., 112., 249., 237.,
       223., 105., 204., 248., 202., 135., 118., 229., 244., 111., 116.,
       240., 113., 194., 150., 123., 232., 195., 196., 197.])

In [38]:
def drop_value(func):
    def wrapper(data):
        if func(data):
            return np.nan
        return data
    return wrapper

In [39]:
drop_height_min_value = drop_value(lambda x: x <= 120 or x >= 210)

In [40]:
drop_height_min_value(220)

nan

In [41]:
user_info2['Height'] = user_info2['Height'].map(drop_height_min_value)

In [42]:
user_info2['Height'].unique()

array([176., 172., 167.,  nan, 171., 177., 164., 170., 178., 182., 184.,
       159., 169., 175., 173., 121., 156., 168., 166., 165., 206., 181.,
       157., 180., 179., 161., 183., 132., 185., 174., 162., 188., 160.,
       158., 134., 155., 126., 163., 187., 186., 192., 201., 208., 152.,
       191., 125., 154., 129., 124., 137., 189., 200., 131., 122., 209.,
       190., 130., 127., 139., 153., 193., 136., 205., 138., 203., 133.,
       207., 149., 128., 151., 204., 202., 135., 194., 150., 123., 195.,
       196., 197.])

** 11.'현재 체중'과	'목표 체중' 컬럼을 정리해주세요. 다음과 같이 정리해주시면 됩니다.** 

* 다양한 형태로 표현되어 있는 몸무게 컬럼(?, ?kg, ? kg 등)을 숫자로 통일해주세요.
* 몸무게가 0으로 되어있으면 NaN으로 바꿔주세요.
* 몸무게가 너무 작거나(40kg 이하) 너무 크면(150kg 이상) 마찬가지로 NaN으로 바꿔주세요.

In [43]:
user_info2.head()

Name Gender   Age  Height Current Weight Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0   176.0             78          68      0.0     주 1회   
1  유세아     여성  39.0   172.0           56kg        51kg      1.0     월 1회   
2  송솔은     여성   NaN   167.0             29          21      1.0     주 1회   
3  백서원     여성  36.0     NaN             67          65      1.0     안 마심   
4  박서은     여성  42.0   167.0             60          57      0.0     안 마심   

    Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
0  010-2292-6251                  0.0       0개월  2016년 07월 05일  2016년 07월 05일   
1    01045795881                  0.0       0개월  2016년 10월 02일  2016년 11월 29일   
2  010-7719-8346                  0.0       0개월  2017년 09월 06일  2017년 09월 06일   
3    01011947169                  0.0       0개월  2017년 06월 02일  2017년 07월 28일   
4  010-2575-6398                  1.0       0개월  2017년 05월 07일  2017년 05월 07일   

   Is Free  
0      1.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0

In [44]:
clean_weight = clean_num_col('kg', '')
user_info2['Current Weight'] = user_info2['Current Weight'].map(clean_weight)
user_info2['Goal Weight'] = user_info2['Goal Weight'].map(clean_weight)

In [45]:
user_info2['Current Weight'].unique()

array([ 78.,  56.,  29.,  67.,  60.,  76.,   0.,  83.,  nan,  84.,  80.,
        81.,  82.,  62.,  59.,  77.,  55.,  75.,  58.,  66.,  63.,  57.,
       142.,  73.,  39.,  85.,  61.,  86.,  65.,  79.,  74.,  52.,  53.,
        64.,  33.,  38.,  72.,  20.,  50.,  68.,  54.,  34.,  88.,  22.,
       121.,  71.,  87.,  30.,  37.,  25.,  70.,  51., 133., 146., 127.,
        35., 134., 131., 135., 120., 138., 132., 130., 141.,  23.,  89.,
        27.,  26., 139.,  24.,  21., 140.,  31.,  69., 145.,  36., 148.,
        49., 136., 123., 129., 126.,  90., 143., 122., 137., 144.,  32.,
       147., 128.,  28., 124., 125.,  48., 149.,  44.,  91.,  92.])

In [46]:
user_info2['Goal Weight'].unique()

array([ 68.,  51.,  21.,  65.,  57.,  73.,   0.,  78.,  58.,  70.,  nan,
        50.,  82.,  77.,  72.,  74.,  75.,  79.,  55.,  80.,  76.,  48.,
        53.,  62.,  54.,  52.,  56.,  71.,  47., 138.,  67.,  29.,  46.,
        69.,  66.,  49.,  81.,  59.,  43.,  30.,  63.,  31.,  10.,  42.,
        61.,  25.,  64.,  60., 113.,  45.,  20.,  32.,  24.,  84.,  83.,
        33.,  28., 132., 143., 122., 126., 124., 131.,  86., 128.,  27.,
       123., 135., 134.,  44.,  26., 136.,  17., 137.,  13., 115., 112.,
        19.,  23.,  14.,  85., 141., 127.,  15., 129., 133.,  18., 121.,
       111.,  88.,  34., 117., 130.,  11.,  22.,  16.,  38., 116.,  41.,
       139., 118., 146.,  40., 114., 140.,  36., 120., 144.,  39., 145.,
        37.,  12., 119.,  87.,  35., 110., 125., 142., 147.,  89., 148.,
        90.])

In [47]:
drop_weight_min_value = drop_value(lambda x: x <= 40 or x >= 150)
user_info2['Current Weight'] = user_info2['Current Weight'].map(drop_weight_min_value)
user_info2['Goal Weight'] = user_info2['Goal Weight'].map(drop_weight_min_value)

In [48]:
user_info2['Current Weight'].unique()

array([ 78.,  56.,  nan,  67.,  60.,  76.,  83.,  84.,  80.,  81.,  82.,
        62.,  59.,  77.,  55.,  75.,  58.,  66.,  63.,  57., 142.,  73.,
        85.,  61.,  86.,  65.,  79.,  74.,  52.,  53.,  64.,  72.,  50.,
        68.,  54.,  88., 121.,  71.,  87.,  70.,  51., 133., 146., 127.,
       134., 131., 135., 120., 138., 132., 130., 141.,  89., 139., 140.,
        69., 145., 148.,  49., 136., 123., 129., 126.,  90., 143., 122.,
       137., 144., 147., 128., 124., 125.,  48., 149.,  44.,  91.,  92.])

In [49]:
user_info2['Goal Weight'].unique()

array([ 68.,  51.,  nan,  65.,  57.,  73.,  78.,  58.,  70.,  50.,  82.,
        77.,  72.,  74.,  75.,  79.,  55.,  80.,  76.,  48.,  53.,  62.,
        54.,  52.,  56.,  71.,  47., 138.,  67.,  46.,  69.,  66.,  49.,
        81.,  59.,  43.,  63.,  42.,  61.,  64.,  60., 113.,  45.,  84.,
        83., 132., 143., 122., 126., 124., 131.,  86., 128., 123., 135.,
       134.,  44., 136., 137., 115., 112.,  85., 141., 127., 129., 133.,
       121., 111.,  88., 117., 130., 116.,  41., 139., 118., 146., 114.,
       140., 120., 144., 145., 119.,  87., 110., 125., 142., 147.,  89.,
       148.,  90.])

### 기본적인 분석을 하기

** 12. 전체 데이터에서 평균/최소/최대 키(cm), 그리고 평균/최소/최대 '현재 체중(kg)'과 '목표 체중(kg)'을 찾아주세요. **

In [50]:
user_info2.head()

Name Gender   Age  Height  Current Weight  Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0   176.0            78.0         68.0      0.0     주 1회   
1  유세아     여성  39.0   172.0            56.0         51.0      1.0     월 1회   
2  송솔은     여성   NaN   167.0             NaN          NaN      1.0     주 1회   
3  백서원     여성  36.0     NaN            67.0         65.0      1.0     안 마심   
4  박서은     여성  42.0   167.0            60.0         57.0      0.0     안 마심   

    Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
0  010-2292-6251                  0.0       0개월  2016년 07월 05일  2016년 07월 05일   
1    01045795881                  0.0       0개월  2016년 10월 02일  2016년 11월 29일   
2  010-7719-8346                  0.0       0개월  2017년 09월 06일  2017년 09월 06일   
3    01011947169                  0.0       0개월  2017년 06월 02일  2017년 07월 28일   
4  010-2575-6398                  1.0       0개월  2017년 05월 07일  2017년 05월 07일   

   Is Free  
0      1.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0

In [51]:
height = user_info2['Height']
'키 평균: {}, 최소: {}, 최대: {}'.format(height.mean(), height.min(), height.max())

'키 평균: 172.05277446230897, 최소: 121.0, 최대: 209.0'

In [52]:
cw = user_info2['Current Weight']
'현재 체중 평균: {}, 최소: {}, 최대: {}'.format(cw.mean(), cw.min(), cw.max())

'현재 체중 평균: 71.85905672477118, 최소: 44.0, 최대: 149.0'

In [53]:
gw = user_info2['Goal Weight']
'목표 체중 평균: {}, 최소: {}, 최대: {}'.format(gw.mean(), gw.min(), gw.max())

'목표 체중 평균: 66.36555729178814, 최소: 41.0, 최대: 148.0'

** 13. 전체 데이터에서 흡연자와 비흡연자 인원의 총합을 찾아주세요. **

In [54]:
user_info2['Smoking'].unique()

array([ 0.,  1., nan])

In [55]:
user_info2['Smoking'].value_counts()

0.0    76932
1.0    19267
Name: Smoking, dtype: int64

In [56]:
user_info2.shape

(106839, 14)

** 14. 전체 데이터에서 유료 사용자와 무료 사용자의 인원의 총합을 찾아주세요. **

또한 유료 사용자만 한정해서, 3개월 / 6개월 / 12개월 결제자의 인원의 총합을 찾아주세요.

In [57]:
user_info2.head()

Name Gender   Age  Height  Current Weight  Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0   176.0            78.0         68.0      0.0     주 1회   
1  유세아     여성  39.0   172.0            56.0         51.0      1.0     월 1회   
2  송솔은     여성   NaN   167.0             NaN          NaN      1.0     주 1회   
3  백서원     여성  36.0     NaN            67.0         65.0      1.0     안 마심   
4  박서은     여성  42.0   167.0            60.0         57.0      0.0     안 마심   

    Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
0  010-2292-6251                  0.0       0개월  2016년 07월 05일  2016년 07월 05일   
1    01045795881                  0.0       0개월  2016년 10월 02일  2016년 11월 29일   
2  010-7719-8346                  0.0       0개월  2017년 09월 06일  2017년 09월 06일   
3    01011947169                  0.0       0개월  2017년 06월 02일  2017년 07월 28일   
4  010-2575-6398                  1.0       0개월  2017년 05월 07일  2017년 05월 07일   

   Is Free  
0      1.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0

In [58]:
user_info2['Paid Plan'].value_counts()

0개월     67472
3개월     19145
6개월      6562
12개월     3020
Name: Paid Plan, dtype: int64

In [59]:
user_info2['Paid Plan'].count()

96199

In [60]:
paid_plan = user_info2['Paid Plan']

In [61]:
(paid_plan == '3개월').sum() + (paid_plan == '6개월').sum() + (paid_plan == '12개월').sum()

28727

In [62]:
paid_plan[(paid_plan=='3개월') | (paid_plan=='6개월') | (paid_plan=='12개월')].count()

28727

** 15. 전체 데이터에서 흡연자와 음주 여부를 바탕으로 다음을 분석해주세요. **
  1. 흡연과 음주를 둘 다 안 하는 사람의 인원 총합.
  1. 흡연은 하지만 음주는 안 하는 사람의 인원 총합.
  1. 흡연은 하지 않지만 음주는 하는 사람의 인원 총합.
  1. 흡연과 음주를 둘 다 하는 사람의 인원 총합.

In [63]:
user_info2.head()

Name Gender   Age  Height  Current Weight  Goal Weight  Smoking Drinking  \
0  안원준     남성  31.0   176.0            78.0         68.0      0.0     주 1회   
1  유세아     여성  39.0   172.0            56.0         51.0      1.0     월 1회   
2  송솔은     여성   NaN   167.0             NaN          NaN      1.0     주 1회   
3  백서원     여성  36.0     NaN            67.0         65.0      1.0     안 마심   
4  박서은     여성  42.0   167.0            60.0         57.0      0.0     안 마심   

    Phone Number  Request Counselling Paid Plan      Joined At     Updated At  \
0  010-2292-6251                  0.0       0개월  2016년 07월 05일  2016년 07월 05일   
1    01045795881                  0.0       0개월  2016년 10월 02일  2016년 11월 29일   
2  010-7719-8346                  0.0       0개월  2017년 09월 06일  2017년 09월 06일   
3    01011947169                  0.0       0개월  2017년 06월 02일  2017년 07월 28일   
4  010-2575-6398                  1.0       0개월  2017년 05월 07일  2017년 05월 07일   

   Is Free  
0      1.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0

In [64]:
user_info2['Drinking'].value_counts()

주 1회    29008
월 2회    28979
월 1회    18948
주 2회     9737
안 마심     9527
Name: Drinking, dtype: int64

In [65]:
user_info2['Drinking'].isnull().sum()

10640

In [66]:
user_info2['Drinking'].unique()

array(['주 1회', '월 1회', '안 마심', '월 2회', nan, '주 2회'], dtype=object)

In [67]:
user_info2['Drinking'].count()

96199

In [68]:
user_info2['IsDrinking'] = 0

In [69]:
user_info2.loc[user_info2['Drinking'] == '주 1회', 'IsDrinking'] = 1
user_info2.loc[user_info2['Drinking'] == '주 2회', 'IsDrinking'] = 1
user_info2.loc[user_info2['Drinking'] == '월 1회', 'IsDrinking'] = 1
user_info2.loc[user_info2['Drinking'] == '월 2회', 'IsDrinking'] = 1
user_info2.loc[user_info2['Drinking'].isna(), 'IsDrinking'] = np.nan

In [70]:
user_info2['IsDrinking'].value_counts()

1.0    86672
0.0     9527
Name: IsDrinking, dtype: int64

In [71]:
user_info2['IsDrinking'].unique()

array([ 1.,  0., nan])

In [72]:
(user_info2['IsDrinking'] == 0).sum()

9527

흡연과 음주를 둘 다 안 하는 사람의 인원 총합.

In [73]:
drinking = user_info2['IsDrinking']
smoking = user_info2['Smoking']

In [74]:
user_info2['Smoking'].unique()

array([ 0.,  1., nan])

In [75]:
len(user_info2[(smoking == 0) & (drinking == 0)])

7638

흡연은 하지만 음주는 안 하는 사람의 인원 총합.

In [76]:
len(user_info2[(smoking == 1) & (drinking == 0)])

1889

흡연은 하지 않지만 음주는 하는 사람의 인원 총합.

In [77]:
len(user_info2[(smoking == 0) & (drinking == 1)])

69294

흡연과 음주를 둘 다 하는 사람의 인원 총합

In [78]:
len(user_info2[(smoking == 1) & (drinking == 1)])

17378

# 과제(중급)

** 16. 성별 컬럼을 정리하기 **

성별 컬럼을 정리해주세요.

데이터를 분석해보면 남성, 여성, 남, 녀, Male, FEMALE 등의 다양한 표현이 있습니다. 이 표현을 male, female으로 통일해주세요.

**17. 전체 인원이 아닌, 남성/여성 각각의 최소/평균/최대 키/몸무게/나이를 구해주세요.**

결과적으로 다음의 수치가 나와야 합니다.
  * 전체 남성의 최소/평균/최대 나이
  * 전체 남성의 최소/평균/최대 몸무게(kg)
  * 전체 남성의 최소/평균/최대 키(cm)
  
  * 전체 여성의 최소/평균/최대 나이
  * 전체 여성의 최소/평균/최대 몸무게(kg)
  * 전체 여성의 최소/평균/최대 키(cm)

** 18. 감량 목표를 분석하기 **

데이터에서 '현재 체중' - '목표 체중' 을 하면 감량 목표가 나올 것입니다. 감량 목표를 찾아서 새로운 컬럼을 만들어주세요.

또한 kg별로 감량을 원하는 사람의 총 인원을 구해주세요. 가령 1) 1kg 감량을 원하는 총 인원, 2) 2kg 감량을 원하는 총 인원, ... 10) 10kg 감량을 원하는 총 인원이 나와야 합니다.

** 19. '가입 개월 수'를 숫자로 표현하기 **

'가입 개월 수' 컬럼을 숫자로 정리해주세요. 현재 3개월, 6개월, 12개월로 되어있는데, 이를 3, 6, 12로 정리하시면 됩니다.

또한 0개월은 0이 아닌 NaN으로 집어넣어 주세요.


** 20. '음주 여부'를 숫자로 표현하기**

'음주 여부' 컬럼을 숫자로 정리해주세요. 현재 1) 주 2회, 2) 주 1회, 3) 월 2회, 4) 월 1회 5) 안 마심으로 되어 있습니다만, 이를 월 기준 음주 횟수로 통일해주세요. 여기서 월은 30일로, 주는 4주로 고정합니다.

가령 1) 주 2회는 8, 2) 주 1회는 4, 3) 월 2회는 2, 4) 월 1회는 1, 5) 안 마심은 0으로 표현하면 됩니다.

## 과제(고급)

** 21.휴대폰 번호 정리하기 **

다양한 표현으로 되어있는 휴대폰 번호를 010-xxxx-xxxx 로 통일해주세요. 가령 휴대폰 번호에 하이픈이 없으면 넣어주시면 됩니다.

또한 unknown으로 되어있거나 비어있는 값은 NaN으로 처리해주세요.

** 22. 날짜를 사용 가능하게 정리하기 **

현재 '회원 가입일' 컬럼과 '회원 정보 갱신일' 컬럼은 20xx년 xx월 xx일 과 같은 형식으로 되어있습니다.

이 데이터를 현재 판다스에서는 날짜 컬럼이 아닌 문자열(텍스트) 컬럼으로 인식하고 있는데, 이 컬럼을 날짜 컬럼으로 인식할 수 있도록 수정해주세요.

** 23. 날짜를 기준으로 분석하기 **

22번에서 날짜 컬럼을 만들었으면 다음을 분석해주세요.

1. 월별 전체 회원 가입량
2. 월 별 유료/무료 회원 가입량의 차이
3. 월 별 남성/여성 회원 가입량의 차이

In [79]:
# Write code here!

** 24. 회원 정보가 맞는지 여부를 확인하는 컬럼을 만들기 **

더 정확한 데이터 분석을 위해서는, 현재까지 고객님이 기업한 회원 정보가 정확한지를 확인하는 작업이 필요합니다. 분석팀에서 데이터를 다음과 같이 정리하면, 오퍼레이션 팀과 코칭 팀이 협업을 통해서 고객 정보를 개선하고, 더 좋은 서비스를 제공할 수 있을 것 같습니다. 다음의 내용이 담겨있는 새로운 컬럼을 하나 만들어주세요. 해당 컬럼에는 reject / counselling / duplicated / confirmed 라는 결과값이 들어가야 합니다.

다음의 경우에는 재기입을 요청한다. (reject)
* 전화번호가 비어있는 경우

다음의 경우는 트레이너와 상담을 유도한다. (counselling)
* 상담 요청(counselling)이 True인 사람.

다음의 경우에는 중복을 확인한다. (duplicated)
* 동일한 이름에 동일한 전화번호를 찾아낸다. 이는 중복되었다고 가정한다.

나머지는 문제가 없다. (confirmed)

In [80]:
# Write code here!

**25. VIP 찾아내기**

다음의 고객을 특별 관리 대상으로 지정합니다. 특별 관리 대상이라고 함은, TKX 서비스의 VIP 플랜을 구매할 확률이 높은 분들을 의미합니다.

1. 트레이너와 상담을 요청한 사람. (counselling)
2. 상담을 요청하지 않은 사람 중, (현재 체중 - 목표 체중) 이 가장 높은 상위 1,000 명.

이 사람들을 특별관리 대상으로 지정하며, VIP라는 이름의 컬럼에 True 값을 넣으면 됩니다. 이후에는 오퍼레이션/코치 팀이 해당 고객님을 개별 컨택하여, 적극적으로 VIP 플랜을 구매하실 수 있도록 노력할 생각입니다. (특별관리 대상이 아닌 분들은 VIP 컬럼에 False 값을 넣으면 됩니다)

또한 전체 데이터와는 별개로, VIP 고객들만을 따로 뽑아내서 CSV파일로 저장할 수 있다면 좋겠습니다.

In [81]:
# Write code here!