# Loading Data from File

- ./data-01-test-score.csv
- EXAM1, EXAM2, EXAM3, FINAL

## numpy slicing

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
a[1:3]

array([2, 3])

In [4]:
a[-1]

5

In [5]:
a[0:2] = 9

In [6]:
a

array([9, 9, 3, 4, 5])

In [7]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
b[:1]

array([[1, 2, 3, 4]])

In [10]:
b[-1]

array([ 9, 10, 11, 12])

In [11]:
b[-1:]

array([[ 9, 10, 11, 12]])

In [12]:
b[0:2, 1]

array([2, 6])

In [13]:
b[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [14]:
b[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
xy = np.loadtxt('./data/data-01-test-score.csv',
                delimiter=',',
                dtype=np.float32)

In [17]:
x_data = xy[:, 0:-1]

In [19]:
y_data = xy[:, [-1]]

In [20]:
print(x_data.shape, x_data, len(x_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25


In [21]:
print(y_data.shape, y_data, len(y_data))

(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 25


In [22]:
test_y_data = xy[:, -1]

In [23]:
print(test_y_data.shape, test_y_data, len(test_y_data))

(25,) [152. 185. 180. 196. 142. 101. 149. 115. 175. 164. 141. 141. 184. 152.
 148. 192. 147. 183. 177. 159. 177. 175. 175. 149. 192.] 25


In [25]:
import tensorflow as tf
import numpy as np

In [26]:
tf.set_random_seed(7777)

In [27]:
xy = np.loadtxt('./data/data-01-test-score.csv',
                delimiter=',',
                dtype=np.float32)

In [29]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [30]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [31]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [32]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [33]:
hypothesis = tf.matmul(X, W) + b

In [35]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [37]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [38]:
train = optimizer.minimize(cost)

In [39]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [41]:
for step in range(2001):
    cost_val, hy_val, _ = \
        sess.run([cost, hypothesis, train],
                 feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val,
              '\nPrediction\n', hy_val)

0 Cost:  6.1598487 
Prediction
 [[153.42183 ]
 [184.22723 ]
 [181.62007 ]
 [199.27675 ]
 [138.9506  ]
 [104.131165]
 [150.9709  ]
 [114.5833  ]
 [173.64156 ]
 [163.69762 ]
 [143.87515 ]
 [142.16966 ]
 [186.28087 ]
 [152.64824 ]
 [151.75499 ]
 [188.30428 ]
 [143.5236  ]
 [182.41298 ]
 [177.38133 ]
 [158.86668 ]
 [176.7237  ]
 [174.10225 ]
 [168.07909 ]
 [151.44753 ]
 [190.40704 ]]
10 Cost:  6.15839 
Prediction
 [[153.41992 ]
 [184.22873 ]
 [181.6196  ]
 [199.27638 ]
 [138.95253 ]
 [104.13326 ]
 [150.96982 ]
 [114.581245]
 [173.64401 ]
 [163.70056 ]
 [143.87505 ]
 [142.1713  ]
 [186.28026 ]
 [152.64775 ]
 [151.75447 ]
 [188.30559 ]
 [143.52412 ]
 [182.41092 ]
 [177.38016 ]
 [158.86526 ]
 [176.7229  ]
 [174.10358 ]
 [168.07797 ]
 [151.44539 ]
 [190.40791 ]]
20 Cost:  6.1569643 
Prediction
 [[153.41803 ]
 [184.23015 ]
 [181.61908 ]
 [199.27599 ]
 [138.95442 ]
 [104.135345]
 [150.9687  ]
 [114.57918 ]
 [173.64641 ]
 [163.70348 ]
 [143.87492 ]
 [142.17287 ]
 [186.27965 ]
 [152.64726 ]
 [151.

290 Cost:  6.121322 
Prediction
 [[153.36963]
 [184.26819]
 [181.60669]
 [199.26636]
 [139.00409]
 [104.18898]
 [150.94008]
 [114.52522]
 [173.7089 ]
 [163.77834]
 [143.87209]
 [142.21394]
 [186.26474]
 [152.63593]
 [151.73996]
 [188.34018]
 [143.53903]
 [182.35464]
 [177.34933]
 [158.82753]
 [176.70102]
 [174.13803]
 [168.04752]
 [151.3888 ]
 [190.43134]]
300 Cost:  6.12011 
Prediction
 [[153.36794]
 [184.26956]
 [181.60628]
 [199.266  ]
 [139.00587]
 [104.19088]
 [150.93907]
 [114.52329]
 [173.7111 ]
 [163.78096]
 [143.872  ]
 [142.2154 ]
 [186.26424]
 [152.63557]
 [151.73946]
 [188.34138]
 [143.5396 ]
 [182.3527 ]
 [177.34831]
 [158.82628]
 [176.70027]
 [174.1392 ]
 [168.04646]
 [151.38692]
 [190.43217]]
310 Cost:  6.1189213 
Prediction
 [[153.36624 ]
 [184.2709  ]
 [181.60583 ]
 [199.26567 ]
 [139.00763 ]
 [104.19277 ]
 [150.93803 ]
 [114.521355]
 [173.71329 ]
 [163.78355 ]
 [143.87189 ]
 [142.21683 ]
 [186.26372 ]
 [152.6352  ]
 [151.73894 ]
 [188.34253 ]
 [143.54013 ]
 [182.35077

760 Cost:  6.0717463 
Prediction
 [[153.29556]
 [184.32747]
 [181.58833]
 [199.25114]
 [139.08208]
 [104.27093]
 [150.894  ]
 [114.4382 ]
 [173.8044 ]
 [163.89044]
 [143.86697]
 [142.2761 ]
 [186.24367]
 [152.62166]
 [151.71631]
 [188.39113]
 [143.56572]
 [182.26805]
 [177.30566]
 [158.77321]
 [176.66667]
 [174.18867]
 [168.00082]
 [151.30815]
 [190.46738]]
770 Cost:  6.070834 
Prediction
 [[153.2941  ]
 [184.32861 ]
 [181.58798 ]
 [199.25082 ]
 [139.08362 ]
 [104.27252 ]
 [150.89304 ]
 [114.436424]
 [173.80624 ]
 [163.89258 ]
 [143.86685 ]
 [142.27728 ]
 [186.24326 ]
 [152.6214  ]
 [151.7158  ]
 [188.3921  ]
 [143.5663  ]
 [182.2663  ]
 [177.30481 ]
 [158.77214 ]
 [176.66595 ]
 [174.18965 ]
 [167.99988 ]
 [151.30661 ]
 [190.46808 ]]
780 Cost:  6.0699134 
Prediction
 [[153.29266 ]
 [184.3298  ]
 [181.58762 ]
 [199.25052 ]
 [139.08517 ]
 [104.27411 ]
 [150.89212 ]
 [114.434654]
 [173.8081  ]
 [163.89474 ]
 [143.86674 ]
 [142.27849 ]
 [186.24287 ]
 [152.62119 ]
 [151.7153  ]
 [188.3931  

1060 Cost:  6.0466785 
Prediction
 [[153.25421 ]
 [184.36118 ]
 [181.57843 ]
 [199.24239 ]
 [139.12679 ]
 [104.316574]
 [150.86688 ]
 [114.386955]
 [173.85764 ]
 [163.95155 ]
 [143.86366 ]
 [142.31035 ]
 [186.23294 ]
 [152.61554 ]
 [151.70175 ]
 [188.41951 ]
 [143.58337 ]
 [182.21753 ]
 [177.28229 ]
 [158.74359 ]
 [176.64621 ]
 [174.21686 ]
 [167.9737  ]
 [151.26471 ]
 [190.48834 ]]
1070 Cost:  6.0459266 
Prediction
 [[153.25288 ]
 [184.36226 ]
 [181.57814 ]
 [199.24211 ]
 [139.1282  ]
 [104.31802 ]
 [150.86601 ]
 [114.385315]
 [173.85931 ]
 [163.95348 ]
 [143.86356 ]
 [142.31145 ]
 [186.23262 ]
 [152.61537 ]
 [151.70128 ]
 [188.42041 ]
 [143.58397 ]
 [182.2159  ]
 [177.28156 ]
 [158.74266 ]
 [176.64555 ]
 [174.21774 ]
 [167.97282 ]
 [151.26337 ]
 [190.48903 ]]
1080 Cost:  6.045173 
Prediction
 [[153.25159]
 [184.36331]
 [181.57782]
 [199.24182]
 [139.12962]
 [104.31946]
 [150.86514]
 [114.38367]
 [173.861  ]
 [163.95538]
 [143.86345]
 [142.3125 ]
 [186.2323 ]
 [152.6152 ]
 [151.7008 ]

1370 Cost:  6.0250826 
Prediction
 [[153.2157  ]
 [184.39299 ]
 [181.56946 ]
 [199.23401 ]
 [139.1692  ]
 [104.358986]
 [150.84065 ]
 [114.33735 ]
 [173.90709 ]
 [164.00734 ]
 [143.86023 ]
 [142.34192 ]
 [186.22372 ]
 [152.61118 ]
 [151.68721 ]
 [188.44588 ]
 [143.60176 ]
 [182.1689  ]
 [177.26125 ]
 [158.7165  ]
 [176.62624 ]
 [174.243   ]
 [167.94762 ]
 [151.22542 ]
 [190.50847 ]]
1380 Cost:  6.024442 
Prediction
 [[153.21452 ]
 [184.39398 ]
 [181.56921 ]
 [199.23378 ]
 [139.17053 ]
 [104.360275]
 [150.83986 ]
 [114.33579 ]
 [173.90863 ]
 [164.00905 ]
 [143.86014 ]
 [142.3429  ]
 [186.22348 ]
 [152.61108 ]
 [151.68677 ]
 [188.4467  ]
 [143.60237 ]
 [182.1674  ]
 [177.26062 ]
 [158.71571 ]
 [176.62563 ]
 [174.24379 ]
 [167.94684 ]
 [151.22426 ]
 [190.50912 ]]
1390 Cost:  6.023803 
Prediction
 [[153.21338]
 [184.39496]
 [181.56894]
 [199.23352]
 [139.17184]
 [104.36158]
 [150.83905]
 [114.33426]
 [173.91014]
 [164.01074]
 [143.86005]
 [142.34384]
 [186.2232 ]
 [152.61098]
 [151.68631]


1660 Cost:  6.008101 
Prediction
 [[153.18318]
 [184.42026]
 [181.56212]
 [199.22682]
 [139.20576]
 [104.39476]
 [150.8177 ]
 [114.29385]
 [173.94887]
 [164.05362]
 [143.85709]
 [142.36833]
 [186.2166 ]
 [152.60863]
 [151.67415]
 [188.46815]
 [143.61899]
 [182.12653]
 [177.2441 ]
 [158.6941 ]
 [176.60863]
 [174.26503]
 [167.925  ]
 [151.1932 ]
 [190.52603]]
1670 Cost:  6.0075793 
Prediction
 [[153.18213]
 [184.42116]
 [181.56187]
 [199.22656]
 [139.20697]
 [104.39593]
 [150.81694]
 [114.29239]
 [173.95023]
 [164.05511]
 [143.85698]
 [142.3692 ]
 [186.21637]
 [152.60855]
 [151.67369]
 [188.46887]
 [143.61957]
 [182.12512]
 [177.24355]
 [158.69336]
 [176.60803]
 [174.26575]
 [167.92422]
 [151.19217]
 [190.52661]]
1680 Cost:  6.0070415 
Prediction
 [[153.18105]
 [184.42204]
 [181.56163]
 [199.22633]
 [139.20818]
 [104.39709]
 [150.81616]
 [114.29095]
 [173.95158]
 [164.0566 ]
 [143.85686]
 [142.37004]
 [186.21614]
 [152.60849]
 [151.67325]
 [188.46957]
 [143.62016]
 [182.12369]
 [177.243 

1900 Cost:  5.9960456 
Prediction
 [[153.15858]
 [184.44115]
 [181.5567 ]
 [199.22125]
 [139.23389]
 [104.42178]
 [150.79977]
 [114.25986]
 [173.98044]
 [164.08803]
 [143.85452]
 [142.38815]
 [186.21161]
 [152.60745]
 [151.6637 ]
 [188.48495]
 [143.63313]
 [182.09358]
 [177.23154]
 [158.67743]
 [176.59479]
 [174.28166]
 [167.90744]
 [151.16946]
 [190.53967]]
1910 Cost:  5.9955807 
Prediction
 [[153.15761]
 [184.44199]
 [181.55647]
 [199.22102]
 [139.23503]
 [104.42287]
 [150.79906]
 [114.25849]
 [173.98169]
 [164.08939]
 [143.85442]
 [142.38893]
 [186.21143]
 [152.6074 ]
 [151.66327]
 [188.48564]
 [143.63371]
 [182.09224]
 [177.23105]
 [158.67676]
 [176.59422]
 [174.28233]
 [167.90672]
 [151.16853]
 [190.5402 ]]
1920 Cost:  5.9951143 
Prediction
 [[153.15663]
 [184.44283]
 [181.55627]
 [199.22081]
 [139.23616]
 [104.42393]
 [150.79834]
 [114.25711]
 [173.98296]
 [164.09076]
 [143.85431]
 [142.38972]
 [186.21123]
 [152.60738]
 [151.66286]
 [188.48631]
 [143.6343 ]
 [182.09093]
 [177.230

In [44]:
# test. Ask my score
print('Your score will be ',
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[185.27939]]


In [46]:
print('Your score will be ',
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101],
                                         [90, 100, 80]]}))

Your score will be  [[185.27939]
 [175.54181]]
