# Loading Data from File

- ./data-01-test-score.csv
- EXAM1, EXAM2, EXAM3, FINAL

In [1]:
import tensorflow as tf

/Users/angelx/.pyenv/versions/3.6.1/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
filename_queue = tf.train.string_input_producer(
    ['./data/data-01-test-score.csv'],
    shuffle=False, name='filename_queue')

In [3]:
reader = tf.TextLineReader()

In [4]:
key, value = reader.read(filename_queue)

In [5]:
record_defaults = [[0.], [0.], [0.], [0.]]

In [6]:
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [7]:
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [8]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [9]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [10]:
hypothesis = tf.matmul(X, W) + b

In [11]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [12]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [13]:
train = optimizer.minimize(cost)

In [14]:
sess = tf.Session()

In [15]:
sess.run(tf.global_variables_initializer())

In [16]:
coord = tf.train.Coordinator()

In [17]:
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [18]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  2425.6187 
Prediction:
 [[ 98.93733 ]
 [130.38904 ]
 [122.35087 ]
 [133.70552 ]
 [102.30102 ]
 [ 78.22201 ]
 [ 98.12327 ]
 [ 69.486885]
 [125.47068 ]
 [118.76426 ]]
10 Cost:  36.91138 
Prediction:
 [[148.3775  ]
 [189.78813 ]
 [180.88966 ]
 [197.46082 ]
 [147.59496 ]
 [111.61587 ]
 [145.856   ]
 [104.887276]
 [180.98047 ]
 [170.18236 ]]
20 Cost:  38.187187 
Prediction:
 [[148.72603]
 [190.17421]
 [181.28697]
 [197.89366]
 [147.88112]
 [111.82324]
 [146.18945]
 [105.14865]
 [181.33386]
 [170.50708]]
30 Cost:  38.00564 
Prediction:
 [[148.74323]
 [190.16211]
 [181.29193]
 [197.8992 ]
 [147.8636 ]
 [111.80672]
 [146.20303]
 [105.17285]
 [181.31512]
 [170.48712]]
40 Cost:  37.814568 
Prediction:
 [[148.75815 ]
 [190.14735 ]
 [181.2942  ]
 [197.90184 ]
 [147.8441  ]
 [111.78876 ]
 [146.2144  ]
 [105.195404]
 [181.29393 ]
 [170.46489 ]]
50 Cost:  37.624638 
Prediction:
 [[148.77301 ]
 [190.13263 ]
 [181.2965  ]
 [197.90448 ]
 [147.82465 ]
 [111.77084 ]
 [146.22577 ]
 [105.217896]
 [

580 Cost:  29.004873 
Prediction:
 [[149.49326]
 [189.41107]
 [181.4022 ]
 [198.03572]
 [146.86636]
 [110.90371]
 [146.79355]
 [106.3422 ]
 [180.25   ]
 [169.38922]]
590 Cost:  28.866638 
Prediction:
 [[149.50566]
 [189.3985 ]
 [181.40396]
 [198.03806]
 [146.84958]
 [110.8888 ]
 [146.80363]
 [106.36219]
 [180.23242]
 [169.37143]]
600 Cost:  28.72926 
Prediction:
 [[149.51804]
 [189.38597]
 [181.40569]
 [198.04039]
 [146.83287]
 [110.87395]
 [146.8137 ]
 [106.38212]
 [180.21489]
 [169.35371]]
610 Cost:  28.59262 
Prediction:
 [[149.53036]
 [189.37349]
 [181.40741]
 [198.0427 ]
 [146.8162 ]
 [110.85913]
 [146.82378]
 [106.40201]
 [180.19742]
 [169.33606]]
620 Cost:  28.456766 
Prediction:
 [[149.54265]
 [189.36104]
 [181.40913]
 [198.04501]
 [146.79955]
 [110.84437]
 [146.8338 ]
 [106.42186]
 [180.18001]
 [169.31847]]
630 Cost:  28.321726 
Prediction:
 [[149.5549  ]
 [189.34862 ]
 [181.41086 ]
 [198.04733 ]
 [146.78296 ]
 [110.82966 ]
 [146.84383 ]
 [106.441666]
 [180.16264 ]
 [169.30096

1170 Cost:  22.0817 
Prediction:
 [[150.16002 ]
 [188.72908 ]
 [181.49214 ]
 [198.16496 ]
 [145.95152 ]
 [110.104095]
 [147.35316 ]
 [107.44813 ]
 [179.30678 ]
 [168.45215 ]]
1180 Cost:  21.983585 
Prediction:
 [[150.17024 ]
 [188.7185  ]
 [181.49347 ]
 [198.16702 ]
 [145.93726 ]
 [110.09185 ]
 [147.36206 ]
 [107.465645]
 [179.29234 ]
 [168.43811 ]]
1190 Cost:  21.885914 
Prediction:
 [[150.18042]
 [188.70795]
 [181.49475]
 [198.16905]
 [145.923  ]
 [110.07964]
 [147.3709 ]
 [107.48312]
 [179.27792]
 [168.42407]]
1200 Cost:  21.788925 
Prediction:
 [[150.1906 ]
 [188.69743]
 [181.49606]
 [198.1711 ]
 [145.90881]
 [110.06748]
 [147.37973]
 [107.50056]
 [179.26358]
 [168.41014]]
1210 Cost:  21.69246 
Prediction:
 [[150.20073 ]
 [188.68692 ]
 [181.49738 ]
 [198.17313 ]
 [145.89467 ]
 [110.05536 ]
 [147.38855 ]
 [107.517944]
 [179.24928 ]
 [168.39624 ]]
1220 Cost:  21.596508 
Prediction:
 [[150.21085 ]
 [188.67647 ]
 [181.49867 ]
 [198.17516 ]
 [145.88055 ]
 [110.043274]
 [147.39735 ]
 [10

1720 Cost:  17.438932 
Prediction:
 [[150.67656]
 [188.18996]
 [181.55577]
 [198.27107]
 [145.22142]
 [109.48699]
 [147.81294]
 [108.35506]
 [178.57884]
 [167.75563]]
1730 Cost:  17.367298 
Prediction:
 [[150.68512 ]
 [188.18091 ]
 [181.55676 ]
 [198.27289 ]
 [145.20914 ]
 [109.47676 ]
 [147.82079 ]
 [108.370514]
 [178.56677 ]
 [167.74431 ]]
1740 Cost:  17.296051 
Prediction:
 [[150.69368]
 [188.1719 ]
 [181.55775]
 [198.27467]
 [145.19687]
 [109.46657]
 [147.82861]
 [108.38594]
 [178.55475]
 [167.73302]]
1750 Cost:  17.22524 
Prediction:
 [[150.7022 ]
 [188.16292]
 [181.55876]
 [198.27647]
 [145.18463]
 [109.45641]
 [147.83643]
 [108.40134]
 [178.54277]
 [167.72179]]
1760 Cost:  17.154858 
Prediction:
 [[150.7107 ]
 [188.15396]
 [181.55974]
 [198.27829]
 [145.17245]
 [109.44629]
 [147.84421]
 [108.41669]
 [178.53082]
 [167.7106 ]]
1770 Cost:  17.084824 
Prediction:
 [[150.71916 ]
 [188.14503 ]
 [181.56075 ]
 [198.28009 ]
 [145.16028 ]
 [109.436195]
 [147.852   ]
 [108.43202 ]
 [178.51

In [19]:
coord.request_stop()
coord.join(threads)