# Multivariable linear regression 

## Hypothesis using matrix

In [1]:
import tensorflow as tf

/Users/angelx/.pyenv/versions/3.6.1/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [4]:
x_data = [[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]]
y_data = [[152], [185], [180], [196], [142]]

In [8]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [9]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [10]:
hypothesis = tf.matmul(X, W) + b

In [11]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [13]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [14]:
train = optimizer.minimize(cost)

In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [16]:
for step in range(2001):
    cost_val, hy_val, _ = \
    sess.run([cost, hypothesis, train],
             feed_dict={X: x_data, Y:y_data})
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  20891.188 
Prediction:
 [[29.251858]
 [26.460531]
 [30.757715]
 [32.32161 ]
 [18.751505]]
10 Cost:  18.42532 
Prediction:
 [[157.0398 ]
 [180.08327]
 [182.10861]
 [197.1407 ]
 [135.93326]]
20 Cost:  18.136972 
Prediction:
 [[157.41003]
 [180.55933]
 [182.56154]
 [197.63568]
 [136.30264]]
30 Cost:  18.040108 
Prediction:
 [[157.39479]
 [180.572  ]
 [182.55789]
 [197.63347]
 [136.31857]]
40 Cost:  17.943827 
Prediction:
 [[157.37842]
 [180.58324]
 [182.5529 ]
 [197.62978]
 [136.33339]]
50 Cost:  17.848114 
Prediction:
 [[157.36209]
 [180.59442]
 [182.54791]
 [197.62607]
 [136.34814]]
60 Cost:  17.752806 
Prediction:
 [[157.3458 ]
 [180.60559]
 [182.54292]
 [197.62239]
 [136.36288]]
70 Cost:  17.658092 
Prediction:
 [[157.32956]
 [180.61674]
 [182.53796]
 [197.61873]
 [136.37756]]
80 Cost:  17.563885 
Prediction:
 [[157.31339]
 [180.62787]
 [182.533  ]
 [197.61507]
 [136.39221]]
90 Cost:  17.470173 
Prediction:
 [[157.29723]
 [180.63893]
 [182.52808]
 [197.6114 ]
 [136.40683]]
10

1060 Cost:  10.419386 
Prediction:
 [[155.92184]
 [181.5826 ]
 [182.1076 ]
 [197.29948]
 [137.65181]]
1070 Cost:  10.364308 
Prediction:
 [[155.90947]
 [181.5911 ]
 [182.10382]
 [197.29669]
 [137.66301]]
1080 Cost:  10.309511 
Prediction:
 [[155.89714]
 [181.59955]
 [182.10005]
 [197.29387]
 [137.67421]]
1090 Cost:  10.254997 
Prediction:
 [[155.88483]
 [181.60802]
 [182.0963 ]
 [197.29108]
 [137.68535]]
1100 Cost:  10.2007885 
Prediction:
 [[155.87254]
 [181.61642]
 [182.09254]
 [197.28828]
 [137.69647]]
1110 Cost:  10.146863 
Prediction:
 [[155.8603 ]
 [181.62483]
 [182.0888 ]
 [197.28549]
 [137.70757]]
1120 Cost:  10.093231 
Prediction:
 [[155.8481 ]
 [181.63321]
 [182.08507]
 [197.28271]
 [137.71863]]
1130 Cost:  10.039895 
Prediction:
 [[155.8359 ]
 [181.64156]
 [182.08133]
 [197.27995]
 [137.72964]]
1140 Cost:  9.986853 
Prediction:
 [[155.82378]
 [181.6499 ]
 [182.07764]
 [197.27718]
 [137.74065]]
1150 Cost:  9.934114 
Prediction:
 [[155.81166]
 [181.65819]
 [182.07393]
 [197.27

1890 Cost:  6.726187 
Prediction:
 [[155.00098]
 [182.21455]
 [181.82626]
 [197.08952]
 [138.48659]]
1900 Cost:  6.691035 
Prediction:
 [[154.99109]
 [182.22131]
 [181.82324]
 [197.08727]
 [138.49556]]
1910 Cost:  6.6561074 
Prediction:
 [[154.98126]
 [182.22809]
 [181.82024]
 [197.085  ]
 [138.50449]]
1920 Cost:  6.6213365 
Prediction:
 [[154.97144]
 [182.23483]
 [181.81723]
 [197.08276]
 [138.5134 ]]
1930 Cost:  6.586735 
Prediction:
 [[154.96164]
 [182.24156]
 [181.81425]
 [197.08052]
 [138.52231]]
1940 Cost:  6.5523577 
Prediction:
 [[154.95186]
 [182.24825]
 [181.81125]
 [197.07828]
 [138.53116]]
1950 Cost:  6.518178 
Prediction:
 [[154.94212]
 [182.25493]
 [181.80827]
 [197.07605]
 [138.54   ]]
1960 Cost:  6.48414 
Prediction:
 [[154.93243]
 [182.26161]
 [181.80531]
 [197.07384]
 [138.54884]]
1970 Cost:  6.4502897 
Prediction:
 [[154.92273]
 [182.26828]
 [181.80237]
 [197.07162]
 [138.55763]]
1980 Cost:  6.4166327 
Prediction:
 [[154.91307]
 [182.27492]
 [181.79941]
 [197.06943]
