# Multivariable linear regression 

## Hypothesis using matrix

In [1]:
import tensorflow as tf

/Users/angelx/.pyenv/versions/3.6.1/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - y))

In [7]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [8]:
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(2001):
    cost_val, hy_val, _ = \
    sess.run([cost, hypothesis, train],
             feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, y: y_data})
    if step % 10 == 0:
        print(step, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  97972.96 
Prediction:
 [-112.05709 -158.80681 -143.96484 -156.83495 -127.23928]
10 Cost:  111.02132 
Prediction:
 [164.63658 173.83463 183.75279 200.0453  126.49807]
20 Cost:  109.53727 
Prediction:
 [165.4336  174.86867 184.73213 201.1157  127.30247]
30 Cost:  108.95235 
Prediction:
 [165.39595 174.8993  184.72287 201.10957 127.34145]
40 Cost:  108.370384 
Prediction:
 [165.35588  174.92686  184.71068  201.10022  127.378044]
50 Cost:  107.79175 
Prediction:
 [165.31592 174.9543  184.69849 201.09085 127.41451]
60 Cost:  107.21627 
Prediction:
 [165.27605 174.98166 184.68636 201.08156 127.45089]
70 Cost:  106.643875 
Prediction:
 [165.23633  175.00897  184.67424  201.07225  127.487175]
80 Cost:  106.07442 
Prediction:
 [165.19667 175.0362  184.66216 201.06296 127.52335]
90 Cost:  105.508316 
Prediction:
 [165.15717 175.06335 184.65013 201.05373 127.55944]
100 Cost:  104.94501 
Prediction:
 [165.11772  175.09042  184.63812  201.04451  127.595436]
110 Cost:  104.384766 
Predictio

1090 Cost:  61.898907 
Prediction:
 [161.70204 177.43738 183.59827 200.23987 130.71959]
1100 Cost:  61.571026 
Prediction:
 [161.67201 177.458   183.58913 200.23271 130.7471 ]
1110 Cost:  61.245197 
Prediction:
 [161.6421  177.47856 183.58005 200.22563 130.77454]
1120 Cost:  60.920776 
Prediction:
 [161.61223 177.49907 183.57095 200.21854 130.80191]
1130 Cost:  60.59832 
Prediction:
 [161.58246 177.51952 183.56187 200.21144 130.82918]
1140 Cost:  60.277626 
Prediction:
 [161.55278 177.53993 183.55287 200.20442 130.8564 ]
1150 Cost:  59.958595 
Prediction:
 [161.52318 177.56026 183.54385 200.19736 130.88354]
1160 Cost:  59.641247 
Prediction:
 [161.49365 177.58057 183.53488 200.19034 130.91061]
1170 Cost:  59.325573 
Prediction:
 [161.46419 177.6008  183.52591 200.18333 130.9376 ]
1180 Cost:  59.01175 
Prediction:
 [161.43483 177.62096 183.51697 200.17636 130.96454]
1190 Cost:  58.699512 
Prediction:
 [161.40555 177.64111 183.50809 200.1694  130.9914 ]
1200 Cost:  58.38906 
Prediction:


In [14]:
for step in range(2001):
    hy_val = \
    sess.run(hypothesis,
             feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, y: y_data})
    if step % 10 == 0:
        print(step, 'Prediction:\n', hy_val)

0 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
10 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
20 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
30 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
40 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
50 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
60 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
70 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
80 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
90 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
100 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
110 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
120 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
130 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
140 Prediction:
 [159.27818 179.10374 182.861

1240 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1250 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1260 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1270 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1280 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1290 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1300 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1310 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1320 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1330 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1340 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1350 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1360 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1370 Prediction:
 [159.27818 179.10374 182.86162 199.65994 132.9461 ]
1380 Prediction:
 [1